spring:
  application.name: hexagonal-architecture
  datasource:
    url: ${DB_URL:jdbc:h2:file:./hexagonal;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL;DATABASE_TO_UPPER=false;}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
